import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, ChevronDown, ChevronRight, Command, FolderOpen, GitBranch, Play, Save, Search, Settings, Sparkles, Terminal, X } from 'lucide-react';
import './styles.css';

type Entry = { name: string; kind: 'file' | 'directory' };
type Tab = { path: string; content: string; dirty: boolean };
type Event = { type: string; state?: string; message?: string; toolName?: string };
type Settings = { provider: string; endpoint: string; model: string; temperature: number; maxTokens: number; apiKeyConfigured: boolean };

function App() {
  const [workspace, setWorkspace] = useState('No workspace open');
  const [entries, setEntries] = useState<Entry[]>([]); const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [tabs, setTabs] = useState<Tab[]>([]); const [active, setActive] = useState(''); const current = tabs.find((tab) => tab.path === active);
  const [terminal, setTerminal] = useState(''); const [command, setCommand] = useState(''); const [panel, setPanel] = useState<'terminal' | 'activity'>('terminal'); const [palette, setPalette] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false); const [apiKeyDraft, setApiKeyDraft] = useState(''); const [settings, setSettings] = useState<Settings>({ provider: 'experimental-labs', endpoint: 'https://api.openai.com/v1', model: '', temperature: .2, maxTokens: 4096, apiKeyConfigured: false }); const [models, setModels] = useState<Array<{ id: string; name: string }>>([]);
  const [prompt, setPrompt] = useState(''); const [mode, setMode] = useState<'ask' | 'plan' | 'agent'>('ask'); const [events, setEvents] = useState<Event[]>([]); const [running, setRunning] = useState(false); const [sessionId, setSessionId] = useState(''); const [sessions, setSessions] = useState<Array<{ id: string; title: string; mode: string; status: string }>>([]); const [permission, setPermission] = useState<{ requestId: string; tool: string; input: unknown } | null>(null);

  useEffect(() => { void window.g1code.getSettings().then(setSettings); const offEvent = window.g1code.onAgentEvent((value) => { const event = value as Event; setEvents((old) => [...old, event]); if (event.type === 'done' || ['COMPLETED', 'FAILED', 'STOPPED'].includes(event.state ?? '')) setRunning(false); setPanel('activity'); }); const offPermission = window.g1code.onPermissionRequest((value) => setPermission(value as { requestId: string; tool: string; input: unknown })); return () => { offEvent(); offPermission(); }; }, []);
  const openWorkspace = async () => { const selected = await window.g1code.chooseWorkspace(); if (selected) { setWorkspace(selected); setEntries(await window.g1code.listDirectory(selected)); } };
  const openFile = async (name: string) => { const filePath = `${workspace}/${name}`; const content = await window.g1code.readFile(filePath); setTabs((old) => old.some((tab) => tab.path === filePath) ? old : [...old, { path: filePath, content, dirty: false }]); setActive(filePath); };
  const save = async () => { if (current) { await window.g1code.writeFile(current.path, current.content); setTabs((old) => old.map((tab) => tab.path === current.path ? { ...tab, dirty: false } : tab)); } };
  const run = async () => { if (!command || workspace === 'No workspace open') return; setTerminal((old) => `${old}\n$ ${command}\n`); const result = await window.g1code.runCommand(command, workspace); setTerminal((old) => `${old}${result.output}\n[exit ${result.exitCode}]\n`); setCommand(''); };
  const startAgent = async () => { if (!prompt.trim() || workspace === 'No workspace open') return; setEvents([]); setRunning(true); try { const result = await window.g1code.startAgent({ workspace, prompt, mode }); setSessionId(result.sessionId); setPrompt(''); } catch (error) { setEvents([{ type: 'error', message: error instanceof Error ? error.message : String(error) }]); setRunning(false); } };
  const loadSessions = async () => { if (workspace !== 'No workspace open') setSessions(await window.g1code.listSessions(workspace)); };
  const stopAgent = () => { if (sessionId) window.g1code.stopAgent(sessionId); };
  const refreshModels = async () => { try { setModels(await window.g1code.getModels()); } catch (error) { setEvents((old) => [...old, { type: 'error', message: error instanceof Error ? error.message : String(error) }]); } };
  const testConnection = async () => { try { const result = await window.g1code.testProvider(settings.model); setModels(result.models); setEvents((old) => [...old, { type: 'state', message: `Connected${result.model ? ` with ${result.model}` : ''}` }]); } catch (error) { setEvents((old) => [...old, { type: 'error', message: error instanceof Error ? error.message : String(error) }]); } };
  useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'p') { event.preventDefault(); setPalette(true); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's') { event.preventDefault(); void save(); } }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); });

  return <div className="app">
    <header className="topbar"><div className="brand"><span className="brand-mark">G1</span><span>G1Code</span><small>AI IDE</small></div><div className="top-actions"><button onClick={() => setPalette(true)}><Command size={14} /> Command Palette</button><button><Search size={15} /> Search</button><button onClick={() => setSettingsOpen(true)}><Settings size={15} /> Settings</button></div></header>
    <div className="workbench"><aside className="activitybar"><button className="active"><FolderOpen size={20} /></button><button><Search size={20} /></button><button><GitBranch size={20} /></button><button onClick={() => setPanel('activity')}><Activity size={20} /></button><div className="activity-spacer" /><button onClick={() => setSettingsOpen(true)}><Settings size={20} /></button></aside>
      <aside className="explorer"><div className="section-title">EXPLORER <button onClick={openWorkspace}><FolderOpen size={15} /></button></div><div className="workspace-name"><ChevronDown size={14} /> {workspace.split(/[\\/]/).pop()}</div>{workspace === 'No workspace open' ? <div className="empty"><FolderOpen size={24} /><p>Open a folder to start</p><button className="primary" onClick={openWorkspace}>Open workspace</button></div> : entries.map((entry) => <button className="file-row" key={entry.name} onClick={() => entry.kind === 'file' ? void openFile(entry.name) : setExpanded((old) => ({ ...old, [entry.name]: !old[entry.name] }))}>{entry.kind === 'directory' ? (expanded[entry.name] ? <ChevronDown size={14} /> : <ChevronRight size={14} />) : <span className="file-dot" />}<span>{entry.name}</span></button>)}</aside>
      <main className="editor-area"><div className="tabs">{tabs.map((tab) => <button className={tab.path === active ? 'tab selected' : 'tab'} key={tab.path} onClick={() => setActive(tab.path)}>{tab.path.split(/[\\/]/).pop()}{tab.dirty && ' •'}<X size={13} onClick={(event) => { event.stopPropagation(); setTabs((old) => old.filter((item) => item.path !== tab.path)); }} /></button>)}</div>{current ? <><div className="editor-header"><span>{current.path.replace(workspace, '').replace(/^[/\\]/, '')}</span><button onClick={() => void save()}><Save size={14} /> Save</button></div><textarea className="editor" value={current.content} onChange={(event) => setTabs((old) => old.map((tab) => tab.path === current.path ? { ...tab, content: event.target.value, dirty: true } : tab))} spellCheck={false} /></> : <div className="welcome"><div className="welcome-icon"><Sparkles size={30} /></div><h1>Build with intent.</h1><p>Open a workspace, configure a provider, and ask G1Code to inspect or change your project.</p><button className="primary" onClick={openWorkspace}><FolderOpen size={15} /> Open workspace</button></div>}<div className="bottom-panel"><div className="panel-tabs"><button className={panel === 'terminal' ? 'selected' : ''} onClick={() => setPanel('terminal')}><Terminal size={14} /> TERMINAL</button><button className={panel === 'activity' ? 'selected' : ''} onClick={() => setPanel('activity')}><Activity size={14} /> AGENT ACTIVITY</button></div>{panel === 'terminal' ? <div className="terminal"><pre>{terminal || 'Terminal ready. Commands run in the active workspace.'}</pre><div className="terminal-input"><span>$</span><input value={command} onChange={(event) => setCommand(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void run()} placeholder="Enter a command" /><button onClick={() => void run()}><Play size={14} /></button></div></div> : <div className="activity-log">{events.length ? events.map((event, index) => <div className="event-row" key={index}><span className={event.type === 'error' ? 'event-error' : 'event-mark'}>{event.type === 'error' ? '!' : '✓'}</span><span><b>{event.state || event.toolName || event.type}</b> {event.message || ''}</span></div>) : <><Bot size={17} /><span>Agent activity will appear here when a task is running.</span></>}</div>}</div></main>
      <aside className="agent"><div className="agent-heading"><div><div className="eyebrow">G1CODE AGENT</div><h2>{running ? 'Working...' : 'Build with intent.'}</h2></div><span className="status-dot" /></div><div className="agent-mode"><button className={mode === 'ask' ? 'selected' : ''} onClick={() => setMode('ask')}>Ask</button><button className={mode === 'plan' ? 'selected' : ''} onClick={() => setMode('plan')}>Plan</button><button className={mode === 'agent' ? 'selected' : ''} onClick={() => setMode('agent')}>Agent</button></div><div className="model-picker"><span>Model</span><select value={settings.model} onChange={(event) => setSettings({ ...settings, model: event.target.value })}><option value="">Select configured model</option>{models.map((model) => <option key={model.id} value={model.id}>{model.name}</option>)}</select><button onClick={() => void refreshModels()}><Activity size={13} /></button></div><div className="agent-empty">{events.length ? <div className="latest-event">{events.slice(-5).map((event, index) => <div key={index}><span className={event.type === 'error' ? 'event-error' : 'event-mark'}>{event.type === 'error' ? '!' : '✓'}</span> {event.message || event.state || event.toolName}</div>)}</div> : <><Bot size={28} /><h3>Ready when you are.</h3><p>Ask about your codebase, plan a change, or start an implementation task.</p><div className="prompt-chip" onClick={() => setPrompt('Explain this project')}>Explain this project <span>↵</span></div><div className="prompt-chip" onClick={() => setPrompt('Find the build command')}>Find the build command <span>↵</span></div></>}</div><div className="agent-input"><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ask G1Code anything..." onKeyDown={(event) => event.key === 'Enter' && !event.shiftKey && (event.preventDefault(), void startAgent())} /><button className="send" onClick={() => void startAgent()} disabled={running}><Sparkles size={16} /></button></div><div className="agent-footer"><span><span className="status-dot" /> {running ? 'Working' : settings.apiKeyConfigured ? 'Provider ready' : 'Provider not configured'}</span><span>{settings.provider}</span></div></aside>
    </div><footer><span><GitBranch size={13} /> main</span><span>Ln 1, Col 1</span><span className="footer-spacer" /><span>UTF-8</span><span>G1Code v0.2</span></footer>
    {palette && <div className="modal-backdrop" onClick={() => setPalette(false)}><div className="palette" onClick={(event) => event.stopPropagation()}><div className="palette-search"><Search size={16} /><input autoFocus placeholder="Type a command" /></div>{['Open Workspace', 'G1Code: Ask Agent', 'G1Code: Plan Task', 'Open AI Settings'].map((item, index) => <button key={item} onClick={() => { setPalette(false); if (index === 0) void openWorkspace(); if (index === 3) setSettingsOpen(true); }}>{item}</button>)}</div></div>}
    {settingsOpen && <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}><div className="settings-card" onClick={(event) => event.stopPropagation()}><div className="settings-title"><div><div className="eyebrow">G1CODE SETTINGS</div><h2>AI Provider</h2></div><button onClick={() => setSettingsOpen(false)}><X size={17} /></button></div><label>Provider<input value={settings.provider} readOnly /></label><label>Endpoint<input value={settings.endpoint} onChange={(event) => setSettings({ ...settings, endpoint: event.target.value })} /></label><label>API key<input type="password" value={apiKeyDraft} placeholder={settings.apiKeyConfigured ? 'Stored securely' : 'Enter API key'} onChange={(event) => setApiKeyDraft(event.target.value)} /></label><label>Model<input value={settings.model} onChange={(event) => setSettings({ ...settings, model: event.target.value })} placeholder="Provider model identifier" /></label><div className="settings-grid"><label>Temperature<input type="number" value={settings.temperature} onChange={(event) => setSettings({ ...settings, temperature: Number(event.target.value) })} /></label><label>Max tokens<input type="number" value={settings.maxTokens} onChange={(event) => setSettings({ ...settings, maxTokens: Number(event.target.value) })} /></label></div><div className="settings-actions"><button className="secondary" onClick={() => void testConnection()}>Test connection</button><button className="primary" onClick={() => void window.g1code.saveSettings({ ...settings, ...(apiKeyDraft ? { apiKey: apiKeyDraft } : {}) }).then(() => { setSettings({ ...settings, apiKeyConfigured: settings.apiKeyConfigured || Boolean(apiKeyDraft) }); setApiKeyDraft(''); setSettingsOpen(false); })}>Save</button></div></div></div>}
    {permission && <div className="modal-backdrop"><div className="settings-card permission-card"><div className="eyebrow">PERMISSION REQUIRED</div><h2>G1Code wants to run {permission.tool}</h2><pre>{JSON.stringify(permission.input, null, 2)}</pre><div className="settings-actions"><button className="secondary" onClick={() => { window.g1code.respondPermission(permission.requestId, false); setPermission(null); }}>Deny</button><button className="primary" onClick={() => { window.g1code.respondPermission(permission.requestId, true); setPermission(null); }}>Allow once</button></div></div></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
